services:
  database:
    image: postgres
    build: ./docker/database/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123456"

  scrapyd:
    image: scrapyd
    build: ./docker/scrapyd/
    ports:
      - "6800:6800"
    expose:
      - "6800"

  prefect:
    image: prefect
    build: ./docker/prefect/
    ports:
      - "4200:4200"
    expose:
      - "4200"
    depends_on:
      - database
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: "postgresql+asyncpg://postgres:123456@database:5432/prefect"
      PREFECT_SERVER_API_HOST: "0.0.0.0"
      PREFECT_LOGGING_SERVER_LEVEL: "DEBUG"

  minehotspot:
    image: minehotspot
    build: ./minehotspot/
    depends_on:
      - prefect
      - database
      - scrapyd
    environment:
      COOKIES_TEXT: "your_cookies"
      DATABASE_CONNECTION_URL: "postgresql+psycopg2://postgres:123456@database:5432/minehotspot"
      SCRAPYD_URL: "http://scrapyd:6800"
      PREFECT_API_URL: "http://prefect:4200/api"
      PREFECT_LOGGING_LEVEL: "DEBUG"
      DOCKER: "1"  # NOTE: docker container environment flag, DON'T change it
      WAIT_PREFECT_SECONDS: "10"  # wait for prefect is ready for serve
      USE_FAKE_DATA: "1"  # NOTE: if 0, crawl the real data; if 1, use the fake data
